CREATE TABLE IF NOT EXISTS BOOK
(
    BOOK_NUMBER      BIGINT      NOT NULL AUTO_INCREMENT,
    BOOK_NAME        VARCHAR(10) NOT NULL,
    PUBLICATION_YEAR VARCHAR(20) NOT NULL,
    BOOK_AUTHOR      VARCHAR(20) NOT NULL,
    PRIMARY KEY (BOOK_NUMBER)
) ENGINE = InnoDB;