DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK
(
    BOOK_NUMBER           BIGINT PRIMARY KEY NOT NULL,
    BOOK_NAME             VARCHAR(255)       NOT NULL,
    BOOK_DESCRIPTION      VARCHAR(5000)      NOT NULL,
    BOOK_AUTHOR           VARCHAR(255)       NOT NULL,
    BOOK_PUBLICATION_YEAR VARCHAR(20)        NOT NULL
);